default: &default
  adapter: postgresql
  encoding: unicode
  username: postgres
  password: 7777
  pool: 5

development:
  <<: *default
  database: rent_a_car_backend_development
  username: postgres
  password: 7777
  host: localhost
  port: 5432

test:
  <<: *default
  database: rent_a_car_backend_test
  username: postgres
  password: 7777

production:
  <<: *default
  database: rent_a_car_backend_production
  username: postgres
  password: 7777
